import React from 'react';
import Head from 'next/head';
import { QueryClient, QueryClientProvider } from 'react-query'
import Layout from '@/app/components/Layout';
import type { AppProps } from 'next/app';
import '@/app/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function MyApp({ Component, pageProps }: AppProps) {
  const [queryClient] = React.useState(() => new QueryClient());
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Add more metadata tags here */}
      </Head>
      <QueryClientProvider client={queryClient}>
        <Layout>
            <Component {...pageProps} />
        </Layout>
      </QueryClientProvider>
    </>
  )
}
